### ISSUE TITLE
Create markteplace banner for the plugin page

### ISSUE THREAD

**Issue by crypt0h3nk** [HydroBlockchain/oc-hydroraindrop-plugin#3]
Create a banner similar to: 

![Banner](https://ps.w.org/wp-hydro-raindrop/assets/banner-772x250.png?rev=1966702)

This banner should have the following dimensions: 837 × 348

**Comment by HarshRajat** [comment]
![octocms-logo](https://user-images.githubusercontent.com/22663032/53351323-150ac780-3947-11e9-8cc1-c2da7e9850d4.jpg)
